package com.link_intersystems.model;

import org.instancio.Instancio;
import org.instancio.generator.specs.OneOfArraySpec;

public class TestDataGen {

    private static final OneOfArraySpec<String> CITIES = Instancio.gen().oneOf(
            "Berlin",
            "Stuttgart",
            "Esslingen am Neckar",
            "Paris",
            "Rome",
            "Madrid",
            "New York",
            "Los Angeles",
            "London",
            "Sydney",
            "Cartagena del Chairá",
            "Moss",
            "Galway",
            "Tver",
            "Woerden",
            "Bila Tserkva",
            "Cellara",
            "Shandong",
            "Hà Nội",
            "Guadalupe",
            "Bünyan",
            "Lviv",
            "Downtown Core",
            "Gorontalo",
            "Essex",
            "Bahawalpur",
            "Invercargill",
            "Tijuana",
            "Itabuna",
            "Shreveport",
            "Secunda",
            "Santander",
            "Canberra",
            "Waidhofen an der Ybbs",
            "Xinjiang",
            "Vallenar",
            "Söderhamn",
            "Ludwigshafen",
            "Marabá",
            "Bojano",
            "Caledon",
            "Asnières-sur-Seine",
            "Tokoroa",
            "Springfield",
            "Värnamo",
            "Legazpi",
            "Whitehorse",
            "Brive-la-Gaillarde",
            "Tây Ninh",
            "Heusden",
            "Jilin",
            "Bremen",
            "Siedlce",
            "Mianwali",
            "Bad Dürkheim",
            "Harstad",
            "Kurram Agency",
            "Dokkum",
            "Vũ Thư",
            "Innsbruck",
            "Chimbarongo",
            "Rocky View",
            "Gjoa Haven",
            "Hebei",
            "Haarlem",
            "Liaoning",
            "Sangju",
            "Jambi",
            "Antalya",
            "Imphal",
            "Thái Nguyên",
            "Palembang",
            "Wels",
            "Khyber Agency",
            "Dosquebradas",
            "Izmail",
            "Anamur",
            "Beypazarı",
            "Tuy Hòa",
            "Santander",
            "Bastia",
            "São João de Meriti",
            "Kupang",
            "Santa Luzia",
            "Hulst",
            "Oslo",
            "Tierralta",
            "Kursk",
            "Dublin",
            "Araban",
            "Hạ Long",
            "Port Harcourt",
            "Gijón",
            "Tapachula",
            "Semarang",
            "Amaro",
            "Gijón",
            "Bydgoszcz",
            "Gölcük",
            "Logan City",
            "Baddeck",
            "Rio Verde",
            "Mandal",
            "Lamitan",
            "Chancay",
            "Muradiye",
            "Sint-Lambrechts-Woluwe",
            "Pica",
            "Sabadell"

    );
    public static final OneOfArraySpec<String> COUNTRIES = Instancio.gen().oneOf(
            "South Africa",
            "Colombia",
            "Pakistan",
            "Vietnam",
            "Costa Rica",
            "Philippines",
            "Ukraine",
            "Australia",
            "Russian Federation",
            "Brazil",
            "Singapore",
            "Australia",
            "Germany",
            "Indonesia",
            "New Zealand",
            "Spain",
            "United States",
            "Turkey",
            "Poland",
            "Italy",
            "France",
            "Greece",
            "Netherlands",
            "United Kingdom",
            "Switzerland"
    );
    public static final OneOfArraySpec<String> ZIP_CODES = Instancio.gen().oneOf(
            "79908",
            "91086",
            "41513",
            "43821",
            "A59 3JD",
            "34265",
            "41098-11174",
            "67396",
            "67542-335",
            "QG14 1GF",
            "62837",
            "13576-29327",
            "645735",
            "583531",
            "12V 2K8",
            "18954",
            "173991",
            "71987",
            "54323",
            "66319",
            "99872",
            "91395",
            "7247",
            "233453",
            "4418 IE",
            "532386",
            "3775",
            "6824",
            "248261",
            "l7X 4W7",
            "7258-5439",
            "01543"
    );
    public static final OneOfArraySpec<String> STREETS = Instancio.gen().oneOf(
            "Ap #711-249 Dapibus Avenue",
            "Ap #857-1069 Ultrices, Street",
            "1478 Diam Rd.",
            "Ap #923-3087 Ultrices, St.",
            "Ap #500-2061 Ut St.",
            "3314 Egestas Road",
            "706-2002 Ut, Street",
            "Ap #848-1098 Lectus Avenue",
            "7985 Faucibus Road",
            "2133 Eleifend Rd.",
            "745-2632 Dictum St.",
            "Ap #176-3679 Ligula Rd.",
            "946-9520 Mauris Ave",
            "Ap #998-4960 Iaculis Ave",
            "7713 Massa. St.",
            "Ap #332-6928 Id Road",
            "Ap #869-6338 Ac Road",
            "P.O. Box 433, 9103 Venenatis Avenue",
            "P.O. Box 600, 3319 Ac St.",
            "416-1652 Sed St.",
            "985-5817 Pede St.",
            "Ap #399-4989 Mattis Street",
            "P.O. Box 927, 2856 Sed St.",
            "207 Egestas Rd.",
            "303-3588 Feugiat. St.",
            "Ap #574-6554 A, St.",
            "705-9218 Ipsum. Avenue",
            "4979 Ac Road",
            "839-7921 Duis Avenue",
            "141-4287 Magna Rd.",
            "473-4621 Eu, Ave",
            "P.O. Box 632, 2338 Tempor Avenue"

    );
    public static final OneOfArraySpec<String> EMAILS = Instancio.gen().oneOf(
            "non.sollicitudin@aol.edu",
            "a@outlook.couk",
            "dictum.sapien@yahoo.edu",
            "neque.in.ornare@yahoo.org",
            "tempor.diam@yahoo.couk",
            "phasellus.dapibus@hotmail.edu",
            "dui@hotmail.edu",
            "lectus.sit@yahoo.org",
            "pede.suspendisse@hotmail.couk",
            "elit.pellentesque@hotmail.org",
            "aliquam.erat@protonmail.edu",
            "in@yahoo.com",
            "vivamus.sit@hotmail.net",
            "pede.sagittis@icloud.ca",
            "natoque.penatibus@outlook.edu",
            "a.mi@aol.com",
            "pede.blandit@yahoo.ca",
            "nunc@hotmail.ca",
            "vel.venenatis@yahoo.com",
            "eu.eleifend@yahoo.edu",
            "dolor@protonmail.ca",
            "scelerisque.mollis@aol.net",
            "feugiat.metus.sit@google.edu",
            "consequat.dolor.vitae@protonmail.net",
            "non@google.net",
            "vestibulum.mauris@hotmail.com",
            "gravida.aliquam.tincidunt@aol.edu",
            "sit@hotmail.org",
            "facilisis@protonmail.couk",
            "lorem@google.com",
            "nibh@aol.ca",
            "quisque.imperdiet@google.ca"
    );
    public static final OneOfArraySpec<String> PHONE_NUMBERS = Instancio.gen().oneOf(
            "(321) 554-2174",
            "(774) 182-6207",
            "1-596-294-1314",
            "1-623-545-7521",
            "(858) 663-1674",
            "1-414-617-0628",
            "1-950-436-6547",
            "(871) 432-5816",
            "1-442-211-9935",
            "1-345-260-2294",
            "(593) 655-6715",
            "1-748-678-0762",
            "1-741-636-4907",
            "(122) 639-6376",
            "1-756-428-4356",
            "(932) 839-5764",
            "1-241-867-4237",
            "(465) 374-7365",
            "(382) 528-7113",
            "1-846-506-6231",
            "(222) 543-2223",
            "(724) 112-3517",
            "(429) 251-3511",
            "1-939-441-8716",
            "1-406-713-0623",
            "(278) 791-5559",
            "1-916-815-2126",
            "1-670-130-8837",
            "1-204-952-4957",
            "(383) 529-3249",
            "(464) 856-4507",
            "1-650-227-4285"
    );
    public static final OneOfArraySpec<String> FIRSTNAMES = Instancio.gen().oneOf(
            "James",
            "Christopher",
            "Ronald",
            "Mary",
            "Lisa",
            "Michelle",
            "John",
            "Daniel",
            "Anthony",
            "Patricia",
            "Nancy",
            "Laura",
            "Robert",
            "Paul",
            "Kevin",
            "Linda",
            "Karen",
            "Sarah",
            "Michael",
            "Mark",
            "Jason",
            "Barbara",
            "Betty",
            "Kimberly",
            "William",
            "Donald",
            "Jeff",
            "Elizabeth",
            "Helen",
            "Deborah",
            "David",
            "George",
            "Jennifer",
            "Sandra",
            "Richard",
            "Kenneth",
            "Maria",
            "Donna",
            "Charles",
            "Steven",
            "Susan",
            "Carol",
            "Joseph",
            "Edward",
            "Margaret",
            "Ruth",
            "Thomas",
            "Brian",
            "Dorothy",
            "Sharon"
    );
    public static final OneOfArraySpec<String> LASTNAMES = Instancio.gen().oneOf(
            "Smith",
            "Anderson",
            "Clark",
            "Wright",
            "Mitchell",
            "Johnson",
            "Thomas",
            "Rodriguez",
            "Lopez",
            "Perez",
            "Williams",
            "Jackson",
            "Lewis",
            "Hill",
            "Roberts",
            "Jones",
            "White",
            "Lee",
            "Scott",
            "Turner",
            "Brown",
            "Harris",
            "Walker",
            "Green",
            "Phillips",
            "Davis",
            "Martin",
            "Hall",
            "Adams",
            "Campbell",
            "Miller",
            "Thompson",
            "Allen",
            "Baker",
            "Parker",
            "Wilson",
            "Garcia",
            "Young",
            "Gonzalez",
            "Evans",
            "Moore",
            "Martinez",
            "Hernandez",
            "Nelson",
            "Edwards",
            "Taylor",
            "Robinson",
            "King",
            "Carter",
            "Collins"
    );


    public static OneOfArraySpec<String> cities() {
        return CITIES;
    }

    public static OneOfArraySpec<String> countries() {
        return COUNTRIES;
    }

    public static OneOfArraySpec<String> zipCodes() {
        return ZIP_CODES;
    }

    public static OneOfArraySpec<String> streets() {
        return STREETS;
    }

    public static OneOfArraySpec<String> emails() {
        return EMAILS;
    }

    public static OneOfArraySpec<String> phoneNumbers() {
        return PHONE_NUMBERS;
    }

    public static OneOfArraySpec<String> firstnames() {
        return FIRSTNAMES;
    }

    public static OneOfArraySpec<String> lastnames() {
        return LASTNAMES;
    }

}
